esphome:
  name: door-lock
  platform: ESP32
  board: esp32cam

wifi:
  ssid: "Wifi"
  password: "Pass"

captive_portal:

logger:

api:

ota:
- platform: esphome
  password: "12345678"


esp32_camera:
  name: "ESP32-CAM Live Stream"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  max_framerate: 10 fps
  resolution: 800x600
  jpeg_quality: 10

# # Ring Bell Button
# binary_sensor:
#   - platform: gpio
#     pin: GPIO13
#     name: "Ring Bell Button"
#     on_press:
#       then:
#         - camera.capture:
#             target: /doorbell_snapshot.jpg
#         - lambda: |-
#             id(telegram).send_photo("/doorbell_snapshot.jpg", "Someone's at the door!");

# Lock Relay
switch:
  - platform: gpio
    pin: GPIO4
    name: "Door Lock"
    id: door_lock

 # Telegram Bot
# telegram_bot:
#   id: telegram
#   token: "YourTelegramBotToken"
#   chat_id: "YourChatID"

# Status Light
status_led:
  pin: GPIO33
