// Baord Configuration 
esphome:
  name: door-lock
  platform: ESP32
  board: esp32cam


// Wifi Configuration
wifi:
  ssid: "SSID"
  password: "PASSWORD"

captive_portal:

logger:

// Api Creation
api:


//OTA Configuration for Witeless Programming
ota:
- platform: esphome
  password: "12345678"


esp32_camera:
  name: "ESP32-CAM Live Stream"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  max_framerate: 10 fps
  resolution: 800x600
  jpeg_quality: 10

# # Ring Bell Button
# binary_sensor:
#   - platform: gpio
#     pin: GPIO13
#     name: "Ring Bell Button"
#     on_press:
#       then:
#         - camera.capture:
#             target: /doorbell_snapshot.jpg
#         - lambda: |-
#             id(telegram).send_photo("/doorbell_snapshot.jpg", "Someone's at the door!");

# Lock Relay
switch:
  - platform: gpio
    pin: GPIO4
    name: "Flash"
    id: cam_flash

  - platform: gpio
    pin: GPIO12
    name: "ringbot_Lock"
    id: ringbot_lock

# binary_sensor:
#   - platform: gpio
#     pin: GPIO16
#     name: "ringbot_pir"
#     id: ringbot_pir
#     device_class: motion


 # Telegram Bot
# telegram_bot:
#   id: telegram
#   token: "YourTelegramBotToken"
#   chat_id: "YourChatID"

# Status Light
status_led:
  pin: GPIO33

